---
  - hosts: all
    become: yes

# Variaveis
    vars:
      - varDB: (ansible_nodename == "database" and ansible_os_family == "RedHat")
      - varWS: (ansible_nodename == "webserver" and ansible_os_family == "Debian") 


    tasks:

# Atualização de sistema.
      - name: Update ubuntu.
        apt:
          update_cache: yes
          upgrade: yes
        when: 
          - ansible_os_family == "Debian"

      - name: Update centos.
        yum:
          name: '*'
          state: latest
          update_cache: yes
        when:
          - ansible_os_family == "RedHat"

# Instalar o postgresql
      - name: Installing PostgreSQL.
        yum:
          name: 
            - postgresql-server
            - vim
            - postgresql-contrib
          state: present
        when: varDB

      - name: Initialize the Database
        shell: postgresql-setup initdb
        when: varDB

      - name: Start/Enable Database.
        service:
          name: postgresql
          state: started
          enabled: yes
        when: varDB

# Instalar o apache
      - name: Installing Apache.
        apt:
          name: apache2
          state: present
        when: varWS

      - name: Start/Enable Apache.
        service:
          name: apache2
          state: started
          enabled: yes
        when: varWS

      - name: Changing apache html page.
        shell: echo "<h1> Hello World! </h1>" > /var/www/html/index.html
        when: varWS

# Instalação do docker
      - name: Install packages to allow apt to use a repository over HTTPS
        apt:
          name: 
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
        when: varWS

      - name: Add Docker’s official GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
        when: varWS
        
      - name: Add docker repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        when: varWS

      - name: Installing Docker
        apt:
          update_cache: yes
          name: 
            - docker-ce
            - docker-ce-cli
            - containerd.io
        when: varWS
