---
  - hosts: all
    become: yes
    tasks:
#      - name: Update ubuntu.
#        apt:
#          update_cache: yes
#          upgrade: yes
#        when: 
#          - ansible_os_family == "Debian"

#      - name: Update centos.
#        yum:
#          name: '*'
#          state: latest
#          update_cache: yes
#        when:
#          - ansible_os_family == "RedHat"

      - name: Installing PostgreSQL.
        yum:
          name: 
            - postgresql-server
            - postgresql-contrib
          state: present
        when:
          - (ansible_nodename == "database" and ansible_os_family == "RedHat")

      - name: Start/Enable Database.
        service:
          name: postgresql
          state: started
          enabled: yes
        when:
          - (ansible_nodename == "database" and ansible_os_family == "RedHat")

      - name: Installing Apache.
        apt:
          name: apache2
          state: present
        when:
          - (ansible_nodename == "webserver" and ansible_os_family == "Debian")

      - name: Start/Enable Apache.
        service:
          name: apache2
          state: started
          enabled: yes
        when:
          - (ansible_nodename == "webserver" and ansible_os_family == "Debian")

      - name: Changing apache html page.
        shell: echo "<h1> Hello World! </h1>" > /var/www/html/index.html
        when:
          - ansible_nodename == "webserver"












