Vagrant.configure("2") do |config|
        config.ssh.forward_x11 = true

# Maquinas

	config.vm.define "ansible" do |ansible|
		ansible.vm.network "private_network", ip: "192.168.254.10"
		ansible.vm.hostname = "ansible"
                ansible.vm.box      = "centos/7"
		ansible.vm.provision "shell", inline:<<-SHELL
			sudo yum update -y --quiet
			sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y --quiet
                        sudo yum install vim git zsh wget python3 ansible -y --quiet
                        wget -q https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O /home/vagrant/install.sh
			chmod +x /home/vagrant/install.sh
			cp /vagrant/Vimcfg/vimrc /home/vagrant/.vimrc 
			echo "\n----------Use ./install.sh to installing Oh My Sh----------\nUser: vagrant\nPass: vagrant\n-----------------------------------------------------------\n" > /etc/motd
		SHELL
	end

	config.vm.define "node1" do |node1|
		node1.vm.network "private_network", ip: "192.168.254.200"
		node1.vm.hostname = "node1"
                node1.vm.box      = "ubuntu/xenial64"
	end

	config.vm.define "node2" do |node2|
		node2.vm.network "private_network", ip: "192.168.254.201"
		node2.vm.hostname = "node2"
                node2.vm.box      = "centos/7"
	end
end
