---
  all:
    children:
      webservers:
        hosts:
          webserver:
            ansible_host: 192.168.254.200

      databases:
        hosts:
          database:
            ansible_host: 192.168.254.201
      
    vars:
      ansible_port: 22
...
