---
  - name: Teste de provisionamento na AWS 
    hosts: localhost
    gather_facts: no
    tasks:
      
      - name: Criando uma key pair
        ec2_key:
          name: ansible
          region: us-east-1
        register: key_pair

      - name: Salvando key pair 
        shell:
          echo -e "{{ key_pair.key.private_key }}" > ansible.pem
        when: key_pair.msg == "key pair created"

      - name: Criando ec2
        ec2:
          assign_public_ip: yes
          group: default 
          image: ami-0915e09cc7ceee3ab 
          wait: yes
          instance_tags:
            Name: ansible
          instance_type: t2.micro
          key_name: ansible
          region: us-east-1
          vpc_subnet_id: subnet-32c5e355
          instance_ids: absent
...
