---
  - name: Instalacao do Apache
    become: yes
    hosts: webservers
    tasks:
      
      - name: Baixando e Instalando o Apache2
        apt:
          name: apache2
          update_cache: yes

      - name: Ativando o processo
        service:
          name: apache2
          state: started
          enabled: yes

      - name: Mudando a pagina inicial do apache
        shell: echo "<h1>Hello World </h1>" > /var/www/html/index.html
...
